# LLM model configuration
llm: "llama-3.1-8b-instant"

# Embeddings configuration
embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"

# Vectorstore persistence directory
persist_dir: "./chroma_store"

# Database file for chat history
db_path: "./outputs/chat_memory.db"

# Other optional runtime settings
temperature: 0.7
top_k: 3
logging: true
